<!DOCTYPE html>
<html>
<head>
    <title>Event Attendee List - {{ $event->title ?? 'All Events' }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1a2845; padding-bottom: 10px; }
        .header h1 { color: #1a2845; margin-bottom: 5px; text-transform: uppercase; font-size: 22px; }
        .header p { margin: 0; color: #666; font-size: 14px; }
        
        .stats-box { background: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #e2e8f0; }
        .stats-grid { width: 100%; }
        .stats-grid td { width: 20%; font-weight: bold; font-size: 11px; }
        .stats-grid span { font-weight: normal; color: #64748b; }

        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #1a2845; color: white; text-align: left; padding: 10px; text-transform: uppercase; font-size: 10px; }
        td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; vertical-align: middle; }
        tr:nth-child(even) { background-color: #f1f5f9; }
        
        .badge { padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; }
        .badge-member { background: #dcfce7; color: #166534; }
        .badge-guest { background: #fef9c3; color: #854d0e; }

        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Attendee Registration List</h1>
        <p>{{ $event->title ?? 'All Active Events' }} | Date: {{ $event->event_date ?? 'N/A' }}</p>
    </div>

    <div class="stats-box">
        <table class="stats-grid">
            <tr>
                <td>Bookings: <span>{{ $bookings->count() }}</span></td>
                <td>Adults: <span>{{ $bookings->sum('adult_count') }}</span></td>
                <td>Children: <span>{{ $bookings->sum('child_count') }}</span></td>
                <td>Infants: <span>{{ $bookings->sum('infant_count') }}</span></td>
                <td>Students: <span>{{ $bookings->sum(fn($b) => $b->student_count) }}</span></td>
            </tr>
        </table>
        <div style="margin-top: 8px; padding-top: 6px; border-top: 1px dashed #cbd5e1; font-size: 9px; color: #64748b; text-align: center;">
            <strong>Legend:</strong> <b>A</b> = Adult &nbsp;|&nbsp; <b>C</b> = Child &nbsp;|&nbsp; <b>I</b> = Infant &nbsp;|&nbsp; <b>S</b> = Student
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="4%">#</th>
                <th width="24%">Attendee Name</th>
                <th width="19%">Event Name</th>
                <th width="15%">Membership No</th>
                <th width="20%">Contact Details</th>
                <th width="18%">Breakdown</th>
            </tr>
        </thead>
        <tbody>
            @foreach($bookings as $index => $b)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td style="font-weight: bold;">
                        {{ $b->full_name }}
                        @if($b->booking_status == 'pending')
                            <br><span style="font-size: 8px; color: #b45309; background: #fef3c7; padding: 1px 4px; border-radius: 3px; font-weight: bold;">PENDING</span>
                        @endif
                    </td>
                    <td style="font-weight: bold; color: #1a2845;">
                        {{ $b->event->title ?? 'N/A' }}
                    </td>
                    <td>
                        @if($b->membership_no && $b->membership_no != 'NON-MEMBER')
                            <span class="badge badge-member">{{ $b->membership_no }}</span>
                        @else
                            <span class="badge badge-guest">NON-MEMBER</span>
                        @endif
                    </td>
                    <td>
                        <div style="font-size: 11px;">{{ $b->email }}</div>
                        <div style="font-size: 10px; color: #666;">{{ $b->phone }}</div>
                    </td>
                    <td>
                        <span style="font-size: 10px; font-weight: bold;">A:{{ $b->adult_count }} | C:{{ $b->child_count }} | I:{{ $b->infant_count }} | S:{{ $b->student_count }}</span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by PMCC-UK Registry System on {{ date('d M Y H:i') }} | Page 1
    </div>
</body>
</html>
